print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("I Love You Xiaoh")
print("Hi,BABY")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
print("nihao world")
